// This file was originally generated by OpenAPI Generator

package com.tranquilmagpie.spring;

import com.fasterxml.jackson.databind.Module;
import org.openapitools.jackson.nullable.JsonNullableModule;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.FullyQualifiedAnnotationBeanNameGenerator;

@SpringBootApplication(
    nameGenerator = FullyQualifiedAnnotationBeanNameGenerator.class
)
@ComponentScan(
    basePackages = {"com.tranquilmagpie.spring", "com.tranquilmagpie.spring.api" , "com.tranquilmagpie.spring.config"},
    nameGenerator = FullyQualifiedAnnotationBeanNameGenerator.class
)
public class TranquilMagpieApiApp {

    public static void main(String[] args) {
        SpringApplication.run(TranquilMagpieApiApp.class, args);
    }

    @Bean(name = "com.tranquilmagpie.spring.TranquilMagpieApiApp.jsonNullableModule")
    public Module jsonNullableModule() {
        return new JsonNullableModule();
    }

}