// This file was originally generated by OpenAPI Generator

package com.tranquilmagpie.spring;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class TranquilMagpieApiAppTests {

    @Test
    void contextLoads() {
    }

}